export const TRUST_CLASSES = [
  {
    id: "I",
    name: "Sovereign Registry Anchored",
    bond: "1–2%",
    risk: "1/6 (lowest)",
    description:
      "Anchored in government-operated registries that publicly record ownership and encumbrances. Fraud requires manipulation of a sovereign registry — legally punishable and institutionally difficult.",
    verification:
      "Registry extract, Reference ID, Licensed verifier confirmation, Encumbrance search",
  },
  {
    id: "II",
    name: "Regulated Custodian Anchored",
    bond: "3–5%",
    risk: "2/6",
    description:
      "Held by a regulated custodian whose records are legally enforceable and subject to regulatory oversight. Fraud requires custodian misrepresentation or collusion with regulated entity.",
    verification:
      "Custodian confirmation letter, Insurance documentation, Physical/ledger audit, Regulatory filing",
  },
  {
    id: "III",
    name: "Dual-Professional Verified",
    bond: "6–8%",
    risk: "3/6",
    description:
      "No authoritative registry or regulated custodian, but ownership validated through independent professional review. Fraud requires coordinated misrepresentation by multiple licensed professionals.",
    verification:
      "Legal opinion letter, Auditor confirmation, Contractual review, Counterparty acknowledgement",
  },
  {
    id: "IV",
    name: "Physical Authentication Anchored",
    bond: "8–12%",
    risk: "4/6",
    description:
      "Existence and ownership depend on physical possession and expert authentication rather than registry entries. Risk includes substitution or forgery.",
    verification:
      "Authentication certificate, Custody confirmation, Insurance validation, Periodic physical inspection",
  },
  {
    id: "V",
    name: "Contractual Claim Anchored",
    bond: "12–20%",
    risk: "5/6",
    description:
      "Represents a contractual right rather than direct ownership. No registry to check, no physical asset to inspect. Trust depends entirely on legal enforceability and counterparty creditworthiness.",
    verification:
      "Dual legal review, Counterparty credit assessment, Contract enforceability opinion, Frequent monitoring",
  },
  {
    id: "VI",
    name: "Oracle / Algorithmically Anchored",
    bond: "20–30%",
    risk: "6/6 (highest)",
    description:
      "Hybrid or derivative assets whose value depends on external data feeds. Weakest real-world anchor. Should be treated cautiously.",
    verification:
      "Oracle audit, Data source verification, Contract enforcement review, Continuous monitoring",
  },
] as const;

export const CATEGORIES = [
  "Real Estate",
  "Government Securities",
  "Private Credit",
  "Commodities & Precious Metals",
  "Corporate Bonds & Fixed Income",
  "Public Equities",
  "Private Equity & Funds",
  "Art & Collectibles",
  "Intellectual Property",
  "Carbon & ESG Credits",
  "Trade Receivables & Invoice Finance",
  "Infrastructure",
];

export const COUNTRIES = [
  { name: "UAE", flag: "🇦🇪", score: "DIFC J=0.85, ADGM J=0.83" },
  { name: "Singapore", flag: "🇸🇬", score: "J=0.92" },
  { name: "United States", flag: "🇺🇸", score: "J=0.88" },
  { name: "United Kingdom", flag: "🇬🇧", score: "J=0.87" },
  { name: "Switzerland", flag: "🇨🇭", score: "J=0.90" },
  { name: "Hong Kong", flag: "🇭🇰", score: "J=0.84" },
  { name: "Cayman Islands", flag: "🇰🇾", score: "J=0.78" },
  { name: "Japan", flag: "🇯🇵", score: "J=0.82" },
  { name: "Germany", flag: "🇩🇪", score: "J=0.89" },
  { name: "Australia", flag: "🇦🇺", score: "J=0.86" },
];

export type AssetClass = {
  id: number;
  name: string;
  category: string;
  trustClass: string;
  registryAnchored: boolean;
  countries: string[];
  description: string;
  marketSize: string;
  growth: string;
  yield: string;
  minInvestment: string;
  registries?: { country: string; status: string; details: string }[];
  custodians?: { country: string; details: string }[];
  keyIssuances?: string[];
  keyPlayers?: string[];
  platforms?: string[];
  note?: string;
  verification?: string;
};

export const ASSET_CLASSES: AssetClass[] = [
  {
    id: 1,
    name: "Residential Property",
    category: "Real Estate",
    trustClass: "I (Sovereign Registry)",
    registryAnchored: true,
    countries: ["UAE", "Singapore", "US", "UK", "Switzerland", "Hong Kong", "Australia", "Germany", "Japan"],
    description:
      "Apartments, villas, houses — fractionalized for investor access. Ownership recorded in sovereign land registries.",
    marketSize: "$20B tokenized",
    growth: "→ $1.4T by 2026 projected",
    yield: "5–9% rental",
    minInvestment: "From AED 2,000 (Dubai)",
    registries: [
      {
        country: "UAE",
        status: "LIVE",
        details:
          "Dubai Land Department (DLD) — Phase 2 live Feb 2026 — 7.8M tokens, secondary market active via PRYPCO Mint on XRP Ledger. Target $16B tokenized by 2033.",
      },
      { country: "Singapore", status: "POSSIBLE", details: "Singapore Land Authority (SLA) — Land titles registered; Project Guardian exploring tokenization." },
      { country: "US", status: "EMERGING", details: "County Recorder / Title Companies — State-by-state; Deloitte projects $4T tokenized RE by 2035." },
      { country: "UK", status: "SANDBOX", details: "HM Land Registry — Digital Securities Sandbox exploring tokenized property." },
      { country: "Hong Kong", status: "POSSIBLE", details: "Land Registry — HKMA exploring Web3 property models." },
    ],
  },
  {
    id: 2,
    name: "Commercial Property",
    category: "Real Estate",
    trustClass: "I (Sovereign Registry)",
    registryAnchored: true,
    countries: ["UAE", "Singapore", "US", "UK", "Switzerland", "Germany"],
    description:
      "Office buildings, retail spaces, warehouses. Higher yields, institutional-grade, registry-anchored.",
    marketSize: "$8B+ tokenized",
    growth: "Fastest growing RE segment",
    yield: "6–12%",
    minInvestment: "$100–$50,000",
    registries: [
      { country: "UAE", status: "LIVE", details: "DLD / ADGM — REES framework covers commercial property." },
      { country: "US", status: "EMERGING", details: "County Records — SPV structures common; RealT and Lofty active." },
    ],
  },
  {
    id: 3,
    name: "Land & Development",
    category: "Real Estate",
    trustClass: "I (Sovereign Registry)",
    registryAnchored: true,
    countries: ["UAE", "US", "Australia"],
    description: "Undeveloped land, development rights, agricultural land. Registry-verifiable but valuation complexity.",
    marketSize: "Early stage",
    growth: "High potential",
    yield: "Capital appreciation",
    minInvestment: "$500+",
    registries: [{ country: "UAE", status: "POSSIBLE", details: "DLD — Land plots eligible under REES framework." }],
  },
  {
    id: 4,
    name: "US Treasuries",
    category: "Government Securities",
    trustClass: "I (Sovereign Registry)",
    registryAnchored: true,
    countries: ["US", "Cayman Islands", "Singapore", "Switzerland"],
    description:
      "Tokenized T-bills and government bonds. Largest RWA segment by value. Used as on-chain cash equivalents.",
    marketSize: "$8.7B on-chain",
    growth: "45% of all tokenized RWA",
    yield: "4.5–5.2%",
    minInvestment: "$5 (Ondo)",
    registries: [
      {
        country: "US",
        status: "LIVE",
        details: "US Treasury / Federal Reserve — BlackRock BUIDL, Franklin Templeton, Ondo USDY all active.",
      },
    ],
  },
  {
    id: 5,
    name: "Sovereign Bonds (Non-US)",
    category: "Government Securities",
    trustClass: "I (Sovereign Registry)",
    registryAnchored: true,
    countries: ["UK", "Germany", "Singapore", "Japan", "Switzerland"],
    description:
      "Government debt instruments from major economies. Registry-anchored through central securities depositories.",
    marketSize: "$1.2B+",
    growth: "Growing rapidly",
    yield: "2–5%",
    minInvestment: "$100+",
    registries: [
      { country: "Germany", status: "EMERGING", details: "Clearstream / Bundesbank — Electronic securities act (eWpG) enables tokenized bonds." },
      { country: "Singapore", status: "LIVE", details: "MAS — Project Guardian exploring tokenized government securities." },
      { country: "Japan", status: "EMERGING", details: "FSA — Crypto bill expected 2026; JPYC stablecoin approved." },
    ],
  },
  {
    id: 6,
    name: "Private Credit Funds",
    category: "Private Credit",
    trustClass: "III (Dual-Professional)",
    registryAnchored: false,
    countries: ["US", "Cayman Islands", "Singapore", "UK"],
    description:
      "Tokenized lending pools, credit funds, short-duration financing. Largest RWA segment by dollar value.",
    marketSize: "$17B tokenized",
    growth: "61% of all tokenized RWA",
    yield: "8–12%",
    minInvestment: "$1,000+",
  },
  {
    id: 7,
    name: "Trade Finance",
    category: "Private Credit",
    trustClass: "III (Dual-Professional)",
    registryAnchored: false,
    countries: ["Singapore", "Hong Kong", "UAE", "UK"],
    description:
      "Letters of credit, invoice discounting, supply chain financing on-chain. Professional verification required.",
    marketSize: "$2B+",
    growth: "High institutional demand",
    yield: "6–10%",
    minInvestment: "$5,000+",
  },
  {
    id: 8,
    name: "Microfinance / DeFi Lending",
    category: "Private Credit",
    trustClass: "V (Contractual Claim)",
    registryAnchored: false,
    countries: ["US", "Cayman Islands", "Singapore"],
    description:
      "Emerging market lending, crypto-native credit. Contractual claim anchored — highest risk class.",
    marketSize: "$800M+",
    growth: "Goldfinch, Maple, Centrifuge leading",
    yield: "10–18%",
    minInvestment: "$100+",
  },
  {
    id: 9,
    name: "Gold & Silver",
    category: "Commodities & Precious Metals",
    trustClass: "II (Regulated Custodian)",
    registryAnchored: false,
    countries: ["Switzerland", "Singapore", "US", "UK", "UAE"],
    description:
      "Physical precious metals in insured vaults, tokenized 1:1. Regulated custodian anchored.",
    marketSize: "$2B+",
    growth: "PAXG + XAUT dominate",
    yield: "Capital appreciation",
    minInvestment: "$50",
    custodians: [
      { country: "Switzerland", details: "Swiss vault operators — LIVE. PAXG and XAUT backed by physical London Good Delivery bars." },
      { country: "Singapore", details: "MAS-regulated vaults — LIVE. Bullion market integration." },
    ],
  },
  {
    id: 10,
    name: "Oil & Energy Commodities",
    category: "Commodities & Precious Metals",
    trustClass: "VI (Oracle / Algorithmic)",
    registryAnchored: false,
    countries: ["UAE", "US", "Singapore"],
    description: "Synthetic exposure to energy commodity prices via oracle feeds. Weakest real-world anchor.",
    marketSize: "Early stage",
    growth: "Synthetic products growing",
    yield: "Variable",
    minInvestment: "$100",
  },
  {
    id: 11,
    name: "Corporate Bonds",
    category: "Corporate Bonds & Fixed Income",
    trustClass: "II (Regulated Custodian)",
    registryAnchored: false,
    countries: ["US", "Switzerland", "Germany", "Singapore", "UK"],
    description: "Investment-grade and high-yield corporate debt. Held by regulated broker-dealers.",
    marketSize: "$3B+",
    growth: "UBS, Goldman active",
    yield: "4–8%",
    minInvestment: "$1,000",
    keyIssuances: [
      "Switzerland: SIX Digital Exchange — LIVE. UBS issued $50M tokenized bond.",
      "Germany: Clearstream — LIVE. eWpG-compliant digital bond issuance.",
    ],
  },
  {
    id: 12,
    name: "Money Market Funds",
    category: "Corporate Bonds & Fixed Income",
    trustClass: "II (Regulated Custodian)",
    registryAnchored: false,
    countries: ["US", "Singapore", "UK"],
    description: "Tokenized MMFs used as collateral and treasury management. Goldman + BNY Mellon active.",
    marketSize: "$7.4B",
    growth: "80% YTD surge in 2025",
    yield: "4.5–5.5%",
    minInvestment: "$100",
    keyPlayers: ["US: SEC-registered — LIVE. BlackRock BUIDL, Franklin OnChain, Ondo USDY."],
  },
  {
    id: 13,
    name: "Tokenized Stocks",
    category: "Public Equities",
    trustClass: "II (Regulated Custodian)",
    registryAnchored: false,
    countries: ["US", "Germany", "Switzerland"],
    description: "Public equity shares tokenized on-chain. Backed by shares held at regulated brokers.",
    marketSize: "$500M+",
    growth: "Nasdaq filed for on-chain trading; Coinbase launched tokenized stocks late 2025",
    yield: "Dividends + appreciation",
    minInvestment: "$1",
    platforms: [
      "US: SEC / FINRA — LIVE. Coinbase tokenized stocks.",
      "Germany: BaFin — LIVE. Backed Finance offers tokenized S&P 500 stocks.",
    ],
  },
  {
    id: 14,
    name: "ETF Shares",
    category: "Public Equities",
    trustClass: "II (Regulated Custodian)",
    registryAnchored: false,
    countries: ["US", "Switzerland"],
    description: "Tokenized index and sector ETFs. BlackRock evaluating ETF tokenization.",
    marketSize: "Early stage",
    growth: "BlackRock evaluating",
    yield: "Market returns",
    minInvestment: "$10+",
  },
  {
    id: 15,
    name: "PE / VC Fund Tokens",
    category: "Private Equity & Funds",
    trustClass: "III (Dual-Professional)",
    registryAnchored: false,
    countries: ["US", "Cayman Islands", "Singapore", "UK"],
    description:
      "LP interests in PE/VC funds. Dual-professional verification — legal opinion + auditor confirmation required.",
    marketSize: "$2B+ alternative funds tokenized",
    growth: "53% of asset managers participating",
    yield: "15–25% target IRR",
    minInvestment: "$10,000+",
  },
  {
    id: 16,
    name: "Revenue Share Agreements",
    category: "Private Equity & Funds",
    trustClass: "V (Contractual Claim)",
    registryAnchored: false,
    countries: ["US", "UK", "Singapore"],
    description: "Profit participation rights tokenized. Pure contractual claim — no registry, no physical asset.",
    marketSize: "Emerging",
    growth: "DeFi integration growing",
    yield: "Variable",
    minInvestment: "$500+",
  },
  {
    id: 17,
    name: "Fine Art",
    category: "Art & Collectibles",
    trustClass: "IV (Physical Authentication)",
    registryAnchored: false,
    countries: ["US", "UK", "Switzerland", "Hong Kong"],
    description:
      "Authenticated paintings, sculptures. Physical possession + expert authentication + secure storage.",
    marketSize: "$200M+",
    growth: "Masterworks pioneering",
    yield: "8–15% historical",
    minInvestment: "$500",
    note: "SEC-registered offerings in US (Masterworks model), expert appraisal required.",
  },
  {
    id: 18,
    name: "Luxury Watches & Collectibles",
    category: "Art & Collectibles",
    trustClass: "IV (Physical Authentication)",
    registryAnchored: false,
    countries: ["Switzerland", "UK", "UAE", "Hong Kong"],
    description:
      "Authenticated luxury items in secure custody. Authentication certificates and insurance required.",
    marketSize: "$50M+",
    growth: "Growing niche",
    yield: "Capital appreciation",
    minInvestment: "$100",
  },
  {
    id: 19,
    name: "Wine & Spirits",
    category: "Art & Collectibles",
    trustClass: "IV (Physical Authentication)",
    registryAnchored: false,
    countries: ["UK", "Switzerland"],
    description: "Fine wine in bonded warehouses. Physical inspection + provenance verification.",
    marketSize: "$30M+",
    growth: "Niche but stable",
    yield: "5–10%",
    minInvestment: "$100",
  },
  {
    id: 20,
    name: "Music Royalties",
    category: "Intellectual Property",
    trustClass: "V (Contractual Claim)",
    registryAnchored: false,
    countries: ["US", "UK"],
    description:
      "Streaming royalties and publishing rights. Contractual claim — depends on platform payment reliability.",
    marketSize: "$100M+",
    growth: "Royal.io, Opulous active",
    yield: "5–15%",
    minInvestment: "$50",
  },
  {
    id: 21,
    name: "Patents & Licensing",
    category: "Intellectual Property",
    trustClass: "V (Contractual Claim)",
    registryAnchored: false,
    countries: ["US", "UK", "Germany", "Japan"],
    description: "Patent portfolios and licensing revenue. Complex legal verification required.",
    marketSize: "Early stage",
    growth: "Emerging use case",
    yield: "Variable",
    minInvestment: "$1,000+",
    note: "USPTO patent ownership is publicly searchable but not blockchain-integrated.",
  },
  {
    id: 22,
    name: "Carbon Credits",
    category: "Carbon & ESG Credits",
    trustClass: "III (Dual-Professional)",
    registryAnchored: false,
    countries: ["US", "Singapore", "UK", "Switzerland", "Australia"],
    description: "Voluntary carbon offsets and RECs tokenized. Professional verification of retirement and validity.",
    marketSize: "$200M+",
    growth: "ESG demand driving growth",
    yield: "Capital appreciation",
    minInvestment: "$10",
    verification: "Verra / Gold Standard registries — Toucan, KlimaDAO bridging verified credits on-chain.",
  },
  {
    id: 23,
    name: "Renewable Energy Certificates",
    category: "Carbon & ESG Credits",
    trustClass: "III (Dual-Professional)",
    registryAnchored: false,
    countries: ["US", "Australia", "Germany"],
    description: "Proof of renewable energy generation. Third-party verified, increasingly tokenized.",
    marketSize: "$50M+",
    growth: "ESG alignment driving adoption",
    yield: "Varies by market",
    minInvestment: "$100",
  },
  {
    id: 24,
    name: "Invoice Finance",
    category: "Trade Receivables & Invoice Finance",
    trustClass: "V (Contractual Claim)",
    registryAnchored: false,
    countries: ["Singapore", "UK", "US", "Hong Kong"],
    description: "Factored invoices and supply chain receivables. Contractual claims on future payments.",
    marketSize: "$1B+",
    growth: "Centrifuge leading",
    yield: "8–15%",
    minInvestment: "$1,000",
  },
  {
    id: 25,
    name: "Litigation Finance",
    category: "Trade Receivables & Invoice Finance",
    trustClass: "V (Contractual Claim)",
    registryAnchored: false,
    countries: ["US", "UK", "Australia"],
    description: "Funding legal claims in exchange for settlement share. Highest risk, highest potential return.",
    marketSize: "$50M+",
    growth: "Niche but growing",
    yield: "15–30%+",
    minInvestment: "$5,000+",
  },
  {
    id: 26,
    name: "Renewable Energy Projects",
    category: "Infrastructure",
    trustClass: "III (Dual-Professional)",
    registryAnchored: false,
    countries: ["UAE", "US", "Germany", "Australia"],
    description: "Solar farms, wind projects, battery storage. Revenue-producing infrastructure tokenized.",
    marketSize: "$300M+",
    growth: "Green finance tailwind",
    yield: "6–10%",
    minInvestment: "$500",
  },
  {
    id: 27,
    name: "Data Centers",
    category: "Infrastructure",
    trustClass: "III (Dual-Professional)",
    registryAnchored: false,
    countries: ["US", "Singapore", "Germany"],
    description:
      "Digital infrastructure with recurring revenue. Professional verification of contracts and capacity.",
    marketSize: "Early stage",
    growth: "AI demand driving interest",
    yield: "8–14%",
    minInvestment: "$1,000+",
  },
];

export const TRUST_CLASS_SUMMARY = [
  { class: "Class I (Registry)", count: 6, assets: "RE residential, RE commercial, Land, US Treasuries, Sovereign bonds (x2)" },
  { class: "Class II (Custodian)", count: 6, assets: "Gold, Corporate bonds, MMFs, Tokenized stocks, ETFs" },
  { class: "Class III (Professional)", count: 7, assets: "Private credit, Trade finance, PE/VC, Carbon credits, RECs, Renewables, Data centers" },
  { class: "Class IV (Physical)", count: 3, assets: "Fine art, Luxury watches, Wine" },
  { class: "Class V (Contractual)", count: 6, assets: "DeFi lending, Revenue shares, Music royalties, Patents, Invoice finance, Litigation" },
  { class: "Class VI (Oracle)", count: 1, assets: "Oil/energy synthetics" },
];

export const MARKET_STATS = [
  { label: "Total RWA tokenized", value: "~$30B+ on public blockchains" },
  { label: "Private credit", value: "~$17B (61% of total)" },
  { label: "US Treasuries", value: "~$8.7B (45% of non-credit RWA)" },
  { label: "Money market funds", value: "~$7.4B (80% YTD surge)" },
  { label: "Commodities (gold-dominated)", value: "~$2B" },
  { label: "Alternative funds", value: "~$2B" },
  { label: "Real estate", value: "$20B (including private structures)" },
  { label: "Dubai DLD tokenization", value: "7.8M tokens, Phase 2 live, target $16B by 2033" },
  { label: "Projected total by 2030", value: "$2T (McKinsey) to $18.9T (BCG/Ripple)" },
  { label: "Projected real estate by 2035", value: "$4T (Deloitte)" },
  { label: "Institutional participation", value: "86% of institutions have or plan exposure" },
  { label: "Active institutional RWA projects", value: "200+ across 40+ financial institutions" },
];
