/**
 * Platform-wide assets — all listed assets from all issuers
 * In production, fetch from API
 */

import { MY_ASSETS } from "./my-assets-data";
import type { MyAssetListing } from "./my-assets-data";

export interface PlatformAsset extends MyAssetListing {
  issuer_name: string;
}

/** All assets on the platform — combines user's assets with other issuers' assets */
export const ALL_PLATFORM_ASSETS: PlatformAsset[] = [
  ...MY_ASSETS.map((a) => ({ ...a, issuer_name: "Enclave Holdings Ltd" })),
  {
    id: "enc-prop-003",
    version: 1,
    status: "funding",
    created_at: "2026-03-02T00:00:00Z",
    updated_at: "2026-03-14T00:00:00Z",
    published_at: "2026-03-06T00:00:00Z",
    issuer_name: "Green Energy Partners",
    hero: {
      title: "Green Energy Fund A — Solar Portfolio",
      asset_type: "commercial",
      asset_type_label: "Renewables",
      images: [{ url: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800", alt: "Solar farm", is_hero: true }],
      key_highlights: ["10MW solar portfolio", "8.5% yield", "PPA-backed"],
      description: "Diversified solar PV portfolio across UAE and KSA.",
    },
    location: { country: "AE", country_name: "UAE", city: "Dubai", district: "—", address_public: "—", registry: { name: "—", reference: "—", status: "n_a" } },
    financials: {
      valuation: { amount_usd: 15_000_000, provider: "DNV", date: "2026-01-15" },
      funding: { target_usd: 15_000_000, raised_usd: 9_000_000, percent_funded: 60, token_price_usd: 100, total_supply: 150_000, tokens_sold: 90_000, tokens_remaining: 60_000, min_investment_usd: 1000 },
      yield: { expected_annual_percent: 8.5, distribution_frequency: "Quarterly", distribution_currency: "USDC" },
    },
    property: { type: "commercial", subtype: "Solar", area_sqft: 0, development_stage: "Operational", tenure: "—" },
    trust: { class: "III", class_name: "Dual-Professional", score: 72, breakdown: { L: 70, V: 75, E: 80, P: 65, R: 70 } },
  },
  {
    id: "enc-prop-004",
    version: 1,
    status: "live",
    created_at: "2026-02-15T00:00:00Z",
    updated_at: "2026-03-10T00:00:00Z",
    published_at: "2026-02-20T00:00:00Z",
    issuer_name: "Marina Asset Management",
    hero: {
      title: "Dubai Logistics Hub — Warehouse A",
      asset_type: "warehouse",
      asset_type_label: "Infrastructure",
      images: [{ url: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800", alt: "Warehouse", is_hero: true }],
      key_highlights: ["Grade A logistics", "7% yield", "Long-term lease"],
      description: "Purpose-built logistics warehouse in Jafza.",
    },
    location: { country: "AE", country_name: "UAE", city: "Dubai", district: "JAFZA", address_public: "JAFZA, Dubai", registry: { name: "JAFZA", reference: "—", status: "verified" } },
    financials: {
      valuation: { amount_usd: 22_000_000, provider: "JLL", date: "2026-01-10" },
      funding: { target_usd: 22_000_000, raised_usd: 22_000_000, percent_funded: 100, token_price_usd: 100, total_supply: 220_000, tokens_sold: 220_000, tokens_remaining: 0, min_investment_usd: 500 },
      yield: { expected_annual_percent: 7, distribution_frequency: "Quarterly", distribution_currency: "USDC" },
    },
    property: { type: "warehouse", subtype: "Logistics", area_sqft: 85000, development_stage: "Completed", tenure: "Freehold" },
    trust: { class: "II", class_name: "Regulated Custodian", score: 85, breakdown: { L: 88, V: 82, E: 90, P: 88, R: 75 } },
  },
  {
    id: "enc-prop-005",
    version: 1,
    status: "funding",
    created_at: "2026-03-05T00:00:00Z",
    updated_at: "2026-03-16T00:00:00Z",
    published_at: "2026-03-08T00:00:00Z",
    issuer_name: "Receivables Finance Co",
    hero: {
      title: "Receivables Pool B — Trade Finance",
      asset_type: "retail",
      asset_type_label: "Receivables",
      images: [{ url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800", alt: "Finance", is_hero: true }],
      key_highlights: ["Invoice financing", "12% yield", "30-day tenor"],
      description: "Pool of verified trade receivables from tier-1 buyers.",
    },
    location: { country: "AE", country_name: "UAE", city: "Dubai", district: "—", address_public: "—", registry: { name: "—", reference: "—", status: "n_a" } },
    financials: {
      valuation: { amount_usd: 5_000_000, provider: "Internal", date: "2026-03-01" },
      funding: { target_usd: 5_000_000, raised_usd: 2_500_000, percent_funded: 50, token_price_usd: 100, total_supply: 50_000, tokens_sold: 25_000, tokens_remaining: 25_000, min_investment_usd: 500 },
      yield: { expected_annual_percent: 12, distribution_frequency: "Monthly", distribution_currency: "USDC" },
    },
    property: { type: "retail", subtype: "Receivables", area_sqft: 0, development_stage: "—", tenure: "—" },
    trust: { class: "V", class_name: "Contractual Claim", score: 58, breakdown: { L: 60, V: 55, E: 65, P: 50, R: 60 } },
  },
  {
    id: "enc-prop-006",
    version: 1,
    status: "under_review",
    created_at: "2026-03-12T00:00:00Z",
    updated_at: "2026-03-17T00:00:00Z",
    published_at: null,
    issuer_name: "Singapore Property Fund",
    hero: {
      title: "Orchard Residences — Unit 18B",
      asset_type: "apartment_block",
      asset_type_label: "Real Estate",
      images: [{ url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800", alt: "Singapore condo", is_hero: true }],
      key_highlights: ["Prime Orchard Rd", "6.8% yield", "SLA verified"],
      description: "Luxury condo in Orchard Road, Singapore.",
    },
    location: { country: "SG", country_name: "Singapore", city: "Singapore", district: "Orchard", address_public: "Orchard Road", registry: { name: "SLA", reference: "SLA-2026-xxx", status: "pending" } },
    financials: {
      valuation: { amount_usd: 4_200_000, provider: "Knight Frank", date: "2026-02-15" },
      funding: { target_usd: 4_200_000, raised_usd: 0, percent_funded: 0, token_price_usd: 100, total_supply: 42_000, tokens_sold: 0, tokens_remaining: 42_000, min_investment_usd: 1000 },
      yield: { expected_annual_percent: 6.8, distribution_frequency: "Quarterly", distribution_currency: "USDC" },
    },
    property: { type: "apartment_block", subtype: "Condo", area_sqft: 2200, bedrooms: 3, bathrooms: 3, development_stage: "Completed", tenure: "Freehold" },
    trust: { class: "I", class_name: "Sovereign Registry", score: 0, breakdown: { L: 0, V: 0, E: 0, P: 0, R: 50 } },
  },
  {
    id: "enc-prop-007",
    version: 1,
    status: "live",
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    published_at: "2026-02-05T00:00:00Z",
    issuer_name: "UK RE Holdings",
    hero: {
      title: "London Docklands — Office Space",
      asset_type: "office",
      asset_type_label: "Real Estate",
      images: [{ url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800", alt: "London office", is_hero: true }],
      key_highlights: ["Canary Wharf", "5.5% yield", "HM Land Registry"],
      description: "Grade A office in London Docklands.",
    },
    location: { country: "GB", country_name: "United Kingdom", city: "London", district: "Docklands", address_public: "Canary Wharf", registry: { name: "HM Land Registry", reference: "—", status: "verified" } },
    financials: {
      valuation: { amount_usd: 18_000_000, provider: "Savills", date: "2026-01-05" },
      funding: { target_usd: 18_000_000, raised_usd: 18_000_000, percent_funded: 100, token_price_usd: 100, total_supply: 180_000, tokens_sold: 180_000, tokens_remaining: 0, min_investment_usd: 1000 },
      yield: { expected_annual_percent: 5.5, distribution_frequency: "Quarterly", distribution_currency: "GBP" },
    },
    property: { type: "office", subtype: "Grade A", area_sqft: 25000, development_stage: "Completed", tenure: "Leasehold" },
    trust: { class: "I", class_name: "Sovereign Registry", score: 91, breakdown: { L: 92, V: 90, E: 95, P: 88, R: 90 } },
  },
  {
    id: "enc-prop-008",
    version: 1,
    status: "funding",
    created_at: "2026-03-08T00:00:00Z",
    updated_at: "2026-03-15T00:00:00Z",
    published_at: "2026-03-10T00:00:00Z",
    issuer_name: "Commodities Token Co",
    hero: {
      title: "Precious Metals Vault — Gold Pool",
      asset_type: "warehouse",
      asset_type_label: "Commodities",
      images: [{ url: "https://images.unsplash.com/photo-1610375461246-83df859d849d?w=800", alt: "Gold", is_hero: true }],
      key_highlights: ["LBMA-approved vault", "Backed by physical gold", "0.5% management fee"],
      description: "Tokenized gold held in LBMA-approved vault.",
    },
    location: { country: "CH", country_name: "Switzerland", city: "Zürich", district: "—", address_public: "—", registry: { name: "Custodian", reference: "—", status: "verified" } },
    financials: {
      valuation: { amount_usd: 10_000_000, provider: "Custodian", date: "2026-03-05" },
      funding: { target_usd: 10_000_000, raised_usd: 6_200_000, percent_funded: 62, token_price_usd: 100, total_supply: 100_000, tokens_sold: 62_000, tokens_remaining: 38_000, min_investment_usd: 500 },
      yield: { expected_annual_percent: 0, distribution_frequency: "—", distribution_currency: "—" },
    },
    property: { type: "warehouse", subtype: "Vault", area_sqft: 0, development_stage: "—", tenure: "—" },
    trust: { class: "II", class_name: "Regulated Custodian", score: 88, breakdown: { L: 90, V: 85, E: 92, P: 90, R: 83 } },
  },
  {
    id: "enc-prop-009",
    version: 1,
    status: "live",
    created_at: "2026-01-20T00:00:00Z",
    updated_at: "2026-02-28T00:00:00Z",
    published_at: "2026-01-25T00:00:00Z",
    issuer_name: "UAE Infrastructure Fund",
    hero: {
      title: "Abu Dhabi Solar Park — Phase 2",
      asset_type: "commercial",
      asset_type_label: "Infrastructure",
      images: [{ url: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800", alt: "Solar", is_hero: true }],
      key_highlights: ["50MW capacity", "Government PPA", "8% yield"],
      description: "Utility-scale solar project in Abu Dhabi.",
    },
    location: { country: "AE", country_name: "UAE", city: "Abu Dhabi", district: "—", address_public: "—", registry: { name: "ADGM", reference: "—", status: "verified" } },
    financials: {
      valuation: { amount_usd: 45_000_000, provider: "DNV", date: "2026-01-01" },
      funding: { target_usd: 45_000_000, raised_usd: 45_000_000, percent_funded: 100, token_price_usd: 100, total_supply: 450_000, tokens_sold: 450_000, tokens_remaining: 0, min_investment_usd: 5000 },
      yield: { expected_annual_percent: 8, distribution_frequency: "Quarterly", distribution_currency: "USDC" },
    },
    property: { type: "commercial", subtype: "Solar", area_sqft: 0, development_stage: "Operational", tenure: "—" },
    trust: { class: "II", class_name: "Regulated Custodian", score: 86, breakdown: { L: 88, V: 84, E: 90, P: 85, R: 82 } },
  },
  {
    id: "enc-prop-010",
    version: 1,
    status: "funding",
    created_at: "2026-03-14T00:00:00Z",
    updated_at: "2026-03-18T00:00:00Z",
    published_at: "2026-03-15T00:00:00Z",
    issuer_name: "Art & Collectibles Ltd",
    hero: {
      title: "Contemporary Art Collection — Lot 7",
      asset_type: "mixed_use",
      asset_type_label: "Art & Collectibles",
      images: [{ url: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800", alt: "Art", is_hero: true }],
      key_highlights: ["Authenticated artwork", "Freeport storage", "Secondary market enabled"],
      description: "Fractional ownership of authenticated contemporary art.",
    },
    location: { country: "CH", country_name: "Switzerland", city: "Geneva", district: "—", address_public: "—", registry: { name: "Authenticator", reference: "—", status: "verified" } },
    financials: {
      valuation: { amount_usd: 2_500_000, provider: "Sotheby's", date: "2026-02-20" },
      funding: { target_usd: 2_500_000, raised_usd: 1_000_000, percent_funded: 40, token_price_usd: 100, total_supply: 25_000, tokens_sold: 10_000, tokens_remaining: 15_000, min_investment_usd: 2000 },
      yield: { expected_annual_percent: 0, distribution_frequency: "—", distribution_currency: "—" },
    },
    property: { type: "mixed_use", subtype: "Art", area_sqft: 0, development_stage: "—", tenure: "—" },
    trust: { class: "IV", class_name: "Physical Authentication", score: 65, breakdown: { L: 65, V: 62, E: 70, P: 68, R: 60 } },
  },
];
